# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3a193a5180a0a37c69e27e0ccc2b1713ced6d6190d1f0756d43d5ec8e69c06ce31d899a6f53cfd5f4a4765afed9f55d82e56832df913398a9149453eba46f62

test:
  secret_key_base: 559a01c310d53dbd23c3de7c222fa03412821506e82ea5672d9675e91e98be9b151b50dce2cd1f3207cd3548df14ef5ec82e1fc0ee2851124d8965bd028e02d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
